test_mode: True

base_model: "klue/roberta-large"

train_csv: "NLP_dataset/train.csv" # train.csv 경로
valid_csv: "NLP_dataset/dev.csv"   # valid.csv 경로

epochs: 1
batch_size: 64
lr: .1e-7

log_name: "klue/roberta-large" # wandb에 logging할 이름.
model_load_path: None # 학습을 이어서 하고자 할 때 경로 지정.
model_save_path: "results/tt.pt" # 학습 완료된 모델을 해당 경로에 저장.(아직 best model 저장 등은 구현 안됨.)

notes: "Auto_Model test."
